### ISSUE TITLE
Remove footnotes in project description

### ISSUE THREAD

**Issue by gucl-mu** [acdh-oeaw/bruckner-kopisten-static#16]
Please remove the double footnotes in the text of the project description. They are currently included as both footnotes and body text.

**Comment by linxOD** [comment]
can you add an example. Footnotes are added to the card-footer with a link the ref link remaining the card-body. Did not see any duplication.

**Comment by gucl-mu** [comment]
Sorry I didn't explain that well enough. So in the project descriptions, the footnotes are all once as text and then the proper footnotes follow
![double footnote](https://user-images.githubusercontent.com/67600420/152306955-250807b1-6df3-43c9-9397-c6d0dcdf150a.PNG)
.

**Comment by gucl-mu** [comment]
https://acdh-oeaw.github.io/bruckner-kopisten-static/01-introduction.html
