### ISSUE TITLE
Data export

### ISSUE THREAD

**Issue by gucl-mu** [acdh-oeaw/bruckner-kopisten-static#18]
I would prefer if the dataset can only be exported as xml. For the lists we would need this function only internally. It can be deleted at the lists. Would it be possible to put the export in the infobox above the citation link?

**Comment by gucl-mu** [comment]
Is it possible to remove the //cell[@ role='Kommentar_intern'] from the TEI/XML export? Or is it easier when i remove it from the github-data?

**Comment by linxOD** [comment]
I m using the original xml and it would be easier to remove it from there. Otherwise I would have to create a new xml file. However, it would be possible to write an xslt that copies all but this cell and we could add it to the Github workflow if you want to keep this data in the original files.

**Comment by gucl-mu** [comment]
ok this is not that important, that we implement another method. i will delete it from the github-data.

**Comment by linxOD** [comment]
resolved
