### ISSUE TITLE
IIIF-Symbol in snippets

### ISSUE THREAD

**Issue by gucl-mu** [acdh-oeaw/bruckner-kopisten-static#21]
in some pictures there is a watermark with "IIIFServer.com". Is this generic or can this be removed?

**Comment by linxOD** [comment]
will check with Peter. Some images are also missing. However, the watermark is at the server.

**Comment by csae8092** [comment]
please provide a link

**Comment by gucl-mu** [comment]
https://acdh-oeaw.github.io/bruckner-kopisten-static/anonymus-073.html

**Comment by csae8092** [comment]
thanks. in your code you are using the actual image endpoint; if you'd use the iiif json endpoint (which I think/know can be done using seadragon) the watermark should be gone
see e.g. https://auden-musulin-papers.github.io/amp-app/amp-transcript__0020.html

another option would be to move the images away from this IIIF server and move to some other server

**Comment by gucl-mu** [comment]
I have two questions about this:
1. could you please reload the images from the gitlab repo? I have changed some images and allocations in the meantime. Therefore some are currently missing.
2. this is also the reason why I consider the overwriting with the iiif json endpoint only conditionally good. There will always be changes in the allocations of the copyists. Replace images, move them, add them. Because I do not know the jsons for the IIIF, it is more difficult for me to take into account when making changes. Question therefore: would it be possible to replace the endpoints only in the build process of the catalog?

**Comment by linxOD** [comment]
The iiif json endpoint is:
https://iiif.acdh.oeaw.ac.at/bruckner-kopisten/

The only information I use form the xml files is the filename:
Trittinger_Adolf_A-WnMus.Hs.19721_A-Clefs_G .png or .jpg

Additionally I add:
/full/full/0/default.jpg

If you change the filenames the images must be manually uploaded again.
If you change the image itself regardless of any filename changes the images must also be uploaded manually. 

I am not sure how to handle this changes especially if I do not know what changed and how?

**Comment by gucl-mu** [comment]
I change some of the files (but take sometimes an exisiting name) or add new images and set the endpoint to the respective samples. All in the gitlab-Repo, so images and references are uptodate there as well as all files in //editions (i sync them with the gitlab ones). These allready have the uptodated endpoint to the image. So I think only the upload from gitlab //101_samples on the IIIF Server has to be redone?

**Comment by linxOD** [comment]
yes but this might become rather time consuming. 
Also I found some problems with the main images:
filename: Rossi_Franz_A-LId477_7_29-[135v]-Alt2-12.jpg
xml ref: Rossi_Franz_A-LId477_7_29-135v-Alt2-12.jpg

square brackets are missing the teixml or the other way round.

**Comment by csae8092** [comment]
images are now served from https://redmine.acdh.oeaw.ac.at/issues/20063 via https://redmine.acdh.oeaw.ac.at/issues/20112 to https://bk-img.acdh-dev.oeaw.ac.at/ so @gucl-mu you can add/delete/rename images via simple filebrowser; @linxOD you need to adapt the url to the images in your xslts
