### ISSUE TITLE
Exclude Vienna from map of table 3 and table 3?

### ISSUE THREAD

**Issue by gucl-mu** [acdh-oeaw/bruckner-kopisten-static#22]
In the coming week we will add Vienna as a location for many copyists. Is it possible that Vienna is excluded in the table 3 but is shown on the map to the total stock? As an example, I have just added Vienna as geodata to the entry for Viktor Christ.

**Comment by linxOD** [comment]
as far as I can see this logic is already in place. Tabelle_residence.xsl contains a rules to exclude "residence=Wien" and has not place Wien in the listPlace el. The Wien example is already visible in the "Gesamt ..." Table. As long as we do not change th above mentioned xsl this should work.
