### ISSUE TITLE
Infobox

### ISSUE THREAD

**Issue by linxOD** [acdh-oeaw/bruckner-kopisten-static#7]
Am Anfang der Datensätze sollte die Box über den Kopisten folgende Informationen beinhalten:
Vorherige Namen: k. A. [xpath: alle t:listPerson/t:person/persName, die not(t:listPerson/t:person/t:persName[@type=‘main‘] sind
Normdaten: k. A. [xpath: concat('https://d-nb.info/gnd/', ./t:listPerson/t:person/t:idno[@type='GND'])]
ABLO / ÖML: siehe ABLO oder ÖML je nachdem welcher Link hinterlegt ist [Link aus: //t:p[@decls='link']/t:ref/@target"/>
                                                <xsl:text>siehe ABLO</xsl:text>]
Residenz: [Ort] [xpath: (//t:person/t:residence]
Zuordnung: [Primär/Sekundär] [xpath: //t:person/t:index/t:term[1]]
Affiliation: [Wiener Kopisten] [xpath: //t:person/t: t:affiliation[@xml:lang='de']]
Zeitraum der Kopiertätigkeit: 1885(?) und später [xpath: (//t:person/t: floruit[1]]
Zitierlink: [Hier weiß ich nicht wie man die am besten macht, aber vermutlich einfach irgendwas mit der ID des Artikels oder? Können wir das jetzt schon umsetzen?

**Comment by gucl-mu** [comment]
Affiliation soll nach Rücksprache mit Projektpartner gelöscht werden.

**Comment by linxOD** [comment]
remove: Affiliation: [Wiener Kopisten] [xpath: //t:person/t: t:affiliation[@xml:lang='de']]
